version: "3.9"

services:

  database:
    image: postgres:15.3-alpine3.18
    container_name: upml-bot-database
    volumes:
      - upml-bot-database-volume:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_OUTSIDE_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  upml-bot:
    image: upml-bot-image
    container_name: upml-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "256M"
    volumes:
      - upml-bot-logs-volume:/app/logs
    env_file: .env
    environment:
      TESSERACT_PATH: "/usr/bin/tesseract"
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    links:
      - database


volumes:
  upml-bot-database-volume:
  upml-bot-logs-volume: