name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo TESSERACT_PATH=${{ secrets.TESSERACT_PATH }} >> .env
          echo TIMEZONE=${{ secrets.TIMEZONE }} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_HOST_PORT=${{ secrets.POSTGRES_HOST_PORT }} >> .env
          echo POSTGRES_OUTSIDE_PORT=${{ secrets.POSTGRES_OUTSIDE_PORT }} >> .env
          echo POSTGRES_DOCKER_PORT=${{ secrets.POSTGRES_DOCKER_PORT }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

      - name: Build and run the Docker
        run: docker compose up -d --build